### PR TITLE
Added signup and login endpoints

### PR DESCRIPTION
**Pull request by EteimZ**
This pull request is for the login and and signup endpoints for the lingo-backend.

### CODE REVIEW

**Review by Diseyi — CHANGES_REQUESTED** [review]
photo_2022-08-18 23 26 56

You are not catching any exeception are you? the try catch block is not necessary, also remove your logs

why are you exposing your connection variables?

**Review by Diseyi — CHANGES_REQUESTED** [review]
photo_2022-08-18 23 36 44

You should store your variables and password in a secret yml file

**Comment by EteimZ** [comment]
> photo_2022-08-18 23 26 56
> 
> You are not catching any exeception are you? the try catch block is not necessary, also remove your logs
> 
> why are you exposing your connection variables?

There's a chance the database connection might fail that's why I am catching the errors.

As for the connection variables, this is a simulation environment. I feel it will make it easy for anyone to give lingo a spin in their local machine.

**Comment by EteimZ** [comment]
> photo_2022-08-18 23 36 44
> 
> You should store your variables and password in a secret yml file

Secret.yml isn't a bad idea but I am focusing on ease of development and hacking around. This won't be the yml file that will be used for the actual deployment.

**Review by Diseyi — APPROVED** [review]

**Pull request merged**
